### ISSUE TITLE
Uninstaller Line 108 broken

### ISSUE THREAD

**Issue by NiiWiiCamo** [NiiWiiCamo/wireguard-configurator#2]
wgc-uninstaller.sh: Zeile 108: Syntaxfehler beim unerwarteten Wort `done'
wgc-uninstaller.sh: Zeile 108: `    done'

wgc-uninstaller.sh: line 108: syntax error near unexpected token `done'
wgc-uninstaller.sh: line 108: `    done'

**Comment by jkoan** [comment]
https://github.com/NiiWiiCamo/wireguard-configurator/blob/b7f23dede0eb0f98db6a9a3fa2517c7803452462/wgc-uninstaller.sh#L101

Here you are :-)
The Backtick is the problem because it would run a command which follows, like here:
https://github.com/NiiWiiCamo/wireguard-configurator/blob/b7f23dede0eb0f98db6a9a3fa2517c7803452462/wgc-installer.sh#L75
This could also been written like this:
```bash
srvprivkey=`wg genkey`
```
But nowadays this syntax is not commonly used as it is harder to read
http://mywiki.wooledge.org/BashFAQ/082

**Comment by NiiWiiCamo** [comment]
Fixed. Not only that, but i also derped the array in some other way...
